"""Initial migration

Revision ID: ba898ff7ed44
Revises: 
Create Date: 2025-01-04 17:11:47.227660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba898ff7ed44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cars_brand', table_name='cars')
    op.drop_column('cars', 'color')
    op.drop_column('cars', 'price')
    op.drop_constraint('orders_car_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_mechanic_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'cars', ['car_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'orders', 'mechanics', ['mechanic_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.create_foreign_key('orders_mechanic_id_fkey', 'orders', 'mechanics', ['mechanic_id'], ['id'])
    op.create_foreign_key('orders_car_id_fkey', 'orders', 'cars', ['car_id'], ['id'])
    op.add_column('cars', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cars', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_cars_brand', 'cars', ['brand'], unique=False)
    # ### end Alembic commands ###
